---
apiVersion: v1
kind: Namespace
metadata:
  name: staging-motopay-ns
  labels:
    name: staging-motopay-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: euphoria-service-deployment
  namespace: staging-motopay-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: euphoria-service
  template:
    metadata:
      labels:
        app: euphoria-service
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
      - name: euphoria-service
        image: swr.af-south-1.myhuaweicloud.com/moto/euphoria-service:15a8d16cacb23ad3b87debb80e5c3c962ad9e3ee
        imagePullPolicy: "IfNotPresent"
        ports:
          - containerPort: 3000
        envFrom:
          - secretRef:
              name: euphoria-secret
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
      imagePullSecrets:
      - name: default-secret
---
apiVersion: v1
kind: Service
metadata:
  name: euphoria-service
  namespace: staging-motopay-ns
spec:
  type: NodePort # Change service type to NodePort
  selector:
    app: euphoria-service
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    #nodePort: 30617 # Define a specific nodePort value (replace with desired port number)

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: kubeissuer-euphoria
  namespace: staging-motopay-ns
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: seun.motopay@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: kubeissuer-euphoria
    # Enable the HTTP-01 challenge provider
    solvers:
    - http01:
        ingress:
          class: nginx

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubecert-euphoria
  namespace: staging-motopay-ns
spec:
  secretName: euphoria
  issuerRef:
    name: kubeissuer-euphoria
    kind: ClusterIssuer
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  commonName: euphoria.staging-api.motopayng.com
  dnsNames:
  - euphoria.staging-api.motopayng.com

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
 name: euphoria-ingress
 namespace: staging-motopay-ns
 annotations:
   #cert-manager.io/cluster-issuer: letsencrypt-staging
   kubernetes.io/ingress.class: nginx
   #nginx.ingress.kubernetes.io/auth-tls-secret: staging-motopay-ns/mp-staging-tls
   #cert-manager.io/cluster-issuer: kubeissuer-adminfe

spec:
 ingressClassName: nginx
 tls:
 - hosts:
   - euphoria.staging-api.motopayng.com
   #secretName: mp-staging-tls
   secretName: euphoria
 rules:
 - host: euphoria.staging-api.motopayng.com
   http:
     paths:
     - pathType: Prefix
       path: /
       backend:
         service:
           name: euphoria-service
           port:
             number: 3000
