import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Euphoria By Sujimoto",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="relative flex flex-col">
          {/* <Navbar /> */}
          {children}
        </div>
      </body>
    </html>
  );
}
