import type { Metadata } from "next";
import "./globals.css";
import LocomotiveScrollProvider from "./LocomotiveScrollProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <div className='relative flex flex-col'>
          {/* <Navbar /> */}
          <LocomotiveScrollProvider>{children}</LocomotiveScrollProvider>
        </div>
      </body>
    </html>
  );
}
